# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: None

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'libraries/cxx-rust-cssparser': '@latest-kf6'

Options:
  test-before-installing: True
  require-passing-tests-on: [ 'Linux' ]
  # Explicitly enable QtWidgets output to make sure we verify it builds
  cmake-options: "-DBUILD_OUTPUT_QTWIDGETS=ON"
