# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: None

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux']
 # Disable PlasmaSVG for now so we do not need RYML in the CI image yet.
 cmake-options: "-DWITH_PLASMASVG_INPUT=OFF"
