# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: None

version = 1

[[annotations]]
path = "**/README.md"
SPDX-License-Identifier = "BSD-2-Clause"
SPDX-FileCopyrightText = "2024 Arjen Hiemstra <ahiemstra@heimr.nl>"

[[annotations]]
path = "doc/*"
SPDX-License-Identifier = "BSD-2-Clause"
SPDX-FileCopyrightText = "2024 Arjen Hiemstra <ahiemstra@heimr.nl>"

[[annotations]]
path = "**/.qmlls.ini"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "None"

[[annotations]]
path = "autotests/TestSelectorData/*.json"
SPDX-License-Identifier = "BSD-2-Clause"
SPDX-FileCopyrightText = "2025 Arjen Hiemstra <ahiemstra@heimr.nl>"
